BShop/Areas/Admin/Controllers/ProductManaController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BShop.Models.Entity;
using BShop.Models.ViewModel;
using BShop.Utils;

namespace BShop.Areas.Admin.Controllers
{
    [CustomAuthorize(Constant.RoleAdmin)]
    public class ProductManaController : Controller
    {
        // GET
        public async Task<ActionResult> Index()
        {
            var list = await DBContext.Instance.Products
                .Include(item => item.Category)
                .Where(item => Constant.Active.Equals(item.Category.Status) && Constant.Active.Equals(item.Status))
                .ToListAsync();
            return View(list);
        }

        public async Task<ActionResult> Add()
        {
            var listCategory = await DBContext.Instance.Categories
                .Where(item => Constant.Active.Equals(item.Status))
                .ToListAsync();
            var categorySelectList = listCategory.Select(item => new SelectListItem()
            {
                Text = item.CategoryName,
                Value = item.CategoryId.ToString()
            }).ToList();

            var model = new ProductViewModel()
            {
                product = new Product() { Price = Decimal.Zero, Discount = decimal.Zero },
                categorySelectList = categorySelectList
            };
            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var product = await DBContext.Instance.Products
                .FirstOrDefaultAsync(item => item.ProductId == id);
            var listCategory = await DBContext.Instance.Categories
                .Where(item => Constant.Active.Equals(item.Status))
                .ToListAsync();
            var categorySelectList = listCategory.Select(item => new SelectListItem()
            {
                Text = item.CategoryName,
                Value = item.CategoryId.ToString()
            }).ToList();
            var model = new ProductViewModel()
            {
                product = product,
                categorySelectList = categorySelectList
            };
            return View(model);
        }


        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> DoAdd(ProductViewModel productViewModel, HttpPostedFileBase img)
        {
            if (!ModelState.IsValid)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Thêm sản phẩm thất bại";
                return View("Add", productViewModel);
            }

            var product = productViewModel.product;

            if (decimal.Compare(product.Price ?? decimal.Zero, product.Discount ?? decimal.Zero) < 0)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Giá khuyến mãi phải nhỏ hơn giá gốc";
                return View("Add", productViewModel);
            }

            if (img != null && img.ContentLength > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await img.InputStream.CopyToAsync(memoryStream);
                    var imageBytes = memoryStream.ToArray();
                    var base64String = Convert.ToBase64String(imageBytes);
                    var mimeType = img.ContentType;
                    product.ProductImage = $"data:{mimeType};base64,{base64String}";
                }
            }

            product.CreatedAt = DateTime.Now;
            product.UpdatedAt = DateTime.Now;
            product.Status = Constant.Active;

            DBContext.Instance.Products.Add(product);
            using (var trans = DBContext.Instance.Database.BeginTransaction())
            {
                try
                {
                    await DBContext.Instance.SaveChangesAsync();
                    trans.Commit();
                    TempData[Constant.StatusRs] = Constant.Success;
                    TempData[Constant.MessageRs] = "Thêm sản phẩm thành công";
                }
                catch (Exception e)
                {
                    trans.Rollback();
                    TempData[Constant.StatusRs] = Constant.Error;
                    TempData[Constant.MessageRs] = "Thêm sản phẩm thất bại: " + e.Message;
                    Console.WriteLine(e);
                }
            }

            return RedirectToAction("Add");
        }

        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> DoUpdate(ProductViewModel productViewModel, HttpPostedFileBase img)
        {
            var p = productViewModel.product;
            var product = await DBContext.Instance.Products.FirstOrDefaultAsync(item => item.ProductId == p.ProductId);

            if (product == null)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Sản phẩm không tồn tại";
                return RedirectToAction("Index");
            }

            if (!ModelState.IsValid)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Cập nhật sản phẩm thất bại";
                return RedirectToAction("Index");
            }

            if (decimal.Compare(p.Price ?? decimal.Zero, p.Discount ?? decimal.Zero) < 0)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Giá khuyến mãi phải nhỏ hơn giá gốc";
                return RedirectToAction("Edit", new { id = p.ProductId });
            }

            if (img != null && img.ContentLength > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await img.InputStream.CopyToAsync(memoryStream);
                    var imageBytes = memoryStream.ToArray();
                    var base64String = Convert.ToBase64String(imageBytes);
                    var mimeType = img.ContentType;
                    product.ProductImage = $"data:{mimeType};base64,{base64String}";
                }
            }

            product.ProductName = p.ProductName;
            product.Price = p.Price;
            product.Discount = p.Discount;
            product.Description = p.Description;
            product.CategoryId = p.CategoryId;
            product.UpdatedAt = DateTime.Now;

            await DBContext.Instance.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        public async Task<ActionResult> Delete(int id)
        {
            var product = await DBContext.Instance.Products.FirstOrDefaultAsync(item => item.ProductId == id);
            if (product == null)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Sản phẩm không tồn tại";
                return RedirectToAction("Index");
            }

            product.Status = Constant.Inactive;
            product.UpdatedAt = DateTime.Now;
            await DBContext.Instance.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

BShop/Areas/Admin/Views/ProductMana/Add.cshtml
@using BShop.Utils
@model BShop.Models.ViewModel.ProductViewModel

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Quản lý sản phẩm", "Thêm sản phẩm" };
}

@section css {
    <script src="https://cdn.ckeditor.com/ckeditor5/41.3.1/super-build/ckeditor.js"></script>
}

@Html.Partial("_PageTitle", pageTitleModel)

@using (Html.BeginForm("DoAdd", "ProductMana", FormMethod.Post, new
        {
            enctype = "multipart/form-data"
        }))
{
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- end card-body -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Tên</label>
                                @Html.TextBoxFor(item => item.product.ProductName, new
                                {
                                    @class = "form-control", @placeholder = "Nhập tên loại"
                                })
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả</label>
                                @Html.TextAreaFor(item => item.product.Description, new
                                {
                                    @class = "form-control",
                                    @placeholder = "Nhập mô tả của bạn vào đây..",
                                    rows = "10",
                                    id = "editor"
                                })
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Giá</label>
                                @Html.TextBoxFor(item => item.product.Price, "{0:N0}", new
                                {
                                    @class = "form-control",
                                    @placeholder = "Nhập giá",
                                    type = "number",
                                    min = "0",
                                    max = "9999999999"
                                })
                                <span class="font-13 text-muted">e.g 123.000.000</span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Giá khi giảm</label>
                                @Html.TextBoxFor(item => item.product.Discount, "{0:N0}", new
                                {
                                    @class = "form-control",
                                    @placeholder = "Nhập giá khi giảm",
                                    type = "number",
                                    min = "0",
                                    max = "9999999999"
                                })
                                <span class="font-13 text-muted">e.g 123.000.000</span>
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Ảnh</label>
                                <input type="file" class="form-control" name="img" placeholder="Chọn ảnh" accept="image/*" id="file-upload"/>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Loại sản phẩm</label>
                                @Html.DropDownListFor(item => item.product.CategoryId,
                                    Model.categorySelectList,
                                    "-- Chọn loại sản phẩm --",
                                    new { @class = "form-select" })
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6" id="uploadPreviewTemplate"></div>
                    </div>
                    <button class="btn btn-sm btn-primary mt-2">Thêm</button>
                    <!-- end row -->
                </div>
            </div> <!-- end card-->
        </div> <!-- end col-->
    </div>
    <!-- end row-->
}

@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
    <script src="~/Scripts/admin/product.add.js"></script>
    <script src="~/Scripts/admin/CKEditor.js"></script>
}

BShop/Areas/Admin/Views/ProductMana/Edit.cshtml
@using BShop.Utils
@model BShop.Models.ViewModel.ProductViewModel

@{
    ViewBag.Title = "Chỉnh sửa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Quản lý sản phẩm", "Chỉnh sửa sản phẩm" };
}

@section css {
    <script src="https://cdn.ckeditor.com/ckeditor5/41.3.1/super-build/ckeditor.js"></script>
}

@Html.Partial("_PageTitle", pageTitleModel)

@using (Html.BeginForm("DoUpdate", "ProductMana", FormMethod.Post, new
        {
            enctype = "multipart/form-data"
        }))
{
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- end card-body -->
                <div class="card-body">
                    <div class="row">
                        @Html.HiddenFor(item => item.product.ProductId)
                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Tên</label>
                                @Html.TextBoxFor(item => item.product.ProductName, new
                                {
                                    @class = "form-control", @placeholder = "Nhập tên loại"
                                })
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mô tả</label>
                                @Html.TextAreaFor(item => item.product.Description, new
                                {
                                    @class = "form-control",
                                    placeholder = "Nhập mô tả của bạn vào đây..",
                                    rows = "10",
                                    id = "editor"
                                })
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Giá</label>
                                @Html.TextBoxFor(item => item.product.Price, new
                                {
                                    @class = "form-control",
                                    @placeholder = "Nhập giá",
                                    type = "number",
                                    min = "0",
                                    max = "9999999999",
                                    step = "1"
                                })
                                <span class="font-13 text-muted">e.g 123.000.000</span>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Giá khi giảm</label>
                                @Html.TextBoxFor(item => item.product.Discount, new
                                {
                                    @class = "form-control",
                                    @placeholder = "Nhập giá khi giảm",
                                    type = "number",
                                    min = "0",
                                    max = "9999999999",
                                    step = "1"
                                })
                                <span class="font-13 text-muted">e.g 123.000.000</span>
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Ảnh</label>
                                <input type="file" class="form-control" name="img" placeholder="Chọn ảnh" accept="image/*" id="file-upload"/>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Loại sản phẩm</label>
                                @Html.DropDownListFor(item => item.product.CategoryId,
                                    Model.categorySelectList,
                                    "-- Chọn loại sản phẩm --",
                                    new { @class = "form-select" })
                            </div>
                        </div> <!-- end col-->

                        <div class="col-xl-6" id="uploadPreviewTemplate"></div>
                    </div>
                    <button class="btn btn-sm btn-primary mt-2">Sửa</button>
                    <!-- end row -->
                </div>
            </div> <!-- end card-->
        </div> <!-- end col-->
    </div>
    <!-- end row-->
}
<script>
    function render() {
        const preview = document.getElementById('uploadPreviewTemplate');
        preview.innerHTML = `
                <div class="card mt-1 mb-0 shadow-none border">
                    <div class="p-2">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <img src=@Url.Content(Model.product.ProductImage) class="avatar-sm rounded bg-light" alt="B Shop">
                            </div>
                            <div class="col ps-0">
                                <a href="javascript:void(0);" class="text-muted fw-bold">@Model.product.ProductName</a>
                                <p class="mb-0" >@Model.product.UpdatedAt</p>
                            </div>
                        </div>
                    </div>
                </div>
                `;
    }
    render();
</script>

@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
    <script src="~/Scripts/admin/product.update.js"></script>
    <script src="~/Scripts/admin/CKEditor.js"></script>

}

BShop/Areas/Admin/Views/ProductMana/Index.cshtml
@using BShop.Utils
@model IEnumerable<BShop.Models.Entity.Product>

@{
    ViewBag.Title = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Sản phẩm", "Quản lý sản phẩm" };
}

@section css {
    <link href="~/Content/admin/dataTables.bootstrap5.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/admin/responsive.bootstrap5.css" rel="stylesheet" type="text/css" />
}


@Html.Partial("_PageTitle", pageTitleModel)


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-centered table-striped dt-responsive nowrap w-100" id="products-datatable">
                        <thead>
                            <tr>
                                <th style="width: 100px;">STT</th>
                                <th>Tên sản phẩm</th>
                                <th>Giá</th>
                                <th>Giá sau khi giảm</th>
                                <th>Ảnh</th>
                                <th>Trạng thái</th>
                                <th style="width: 75px;">#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var (value, index) in Model.Select((v, i) => (v, i)))
                            {
                                <tr>
                                    <td>
                                        @(index + 1)
                                    </td>
                                    <td class="table-user">
                                        <a href="javascript:void(0);" class="text-body fw-semibold">@value.ProductName</a>
                                    </td>
                                    <td>
                                        @($"{value.Price:n0}") đ
                                    </td>

                                    <td>
                                        @($"{value.Discount:n0}") đ
                                    </td>

                                    <td>
                                        <img src="@value.ProductImage" alt="B shop" 
                                             style="width: 100px; height: 100px; object-fit: cover;"/>
                                    </td>
                                    <td>
                                        @{
                                            var css = Constant.Active.Equals(value.Status) ? "success" : Constant.Block.Equals(value.Status) ? "danger" : "warning";
                                        }
                                        <span class="badge badge-@css-lighten">@value.Status</span>
                                    </td>

                                    <td>
                                        <a href="/Admin/ProductMana/Edit/@value.ProductId" class="action-icon" title="Chỉnh sửa">
                                            <i class="mdi mdi-square-edit-outline"></i>
                                        </a>
                                        <a href="/Admin/ProductMana/Delete/@value.ProductId" class="action-icon" title="Xóa">
                                            <i class="mdi mdi-delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
<!-- end row -->



@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
    <script src="~/Scripts/admin/product.index.js"></script>
}