BShop/Areas/Admin/Controllers/CategoryManaController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BShop.Models.Entity;
using BShop.Utils;

namespace BShop.Areas.Admin.Controllers
{
    [CustomAuthorize(Constant.RoleAdmin)]
    public class CategoryManaController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var listCategory = await DBContext.Instance.Categories
                .Where(item => Constant.Active.Equals(item.Status))
                .ToListAsync();
            return View(listCategory);
        }

        public ActionResult Add()
        {
            return View(new Category());
        }

        public async Task<ActionResult> Edit(int id)
        {
            var category = await DBContext.Instance.Categories
                .FirstOrDefaultAsync(item => item.CategoryId == id);
            return View(category);
        }

        [HttpPost]
        public async Task<ActionResult> DoAdd(Category cate)
        {
            if (!ModelState.IsValid)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Thêm danh mục thất bại";
                return View("Add", cate);
            }

            cate.CreatedAt = DateTime.Now;
            cate.UpdatedAt = DateTime.Now;
            cate.Status = Constant.Active;
            DBContext.Instance.Categories.Add(cate);
            await DBContext.Instance.SaveChangesAsync();

            TempData[Constant.StatusRs] = Constant.Success;
            TempData[Constant.MessageRs] = "Thêm danh mục thành công";
            return RedirectToAction("Add");
        }

        [HttpPost]
        public async Task<ActionResult> DoUpdate(Category cate)
        {
            var category = await DBContext.Instance.Categories
                .FirstOrDefaultAsync(item => item.CategoryId == cate.CategoryId);
            if (category == null)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Danh mục không tồn tại";
                return RedirectToAction("Index");
            }

            category.CategoryName = cate.CategoryName;
            category.UpdatedAt = DateTime.Now;
            await DBContext.Instance.SaveChangesAsync();
            TempData[Constant.StatusRs] = Constant.Success;
            TempData[Constant.MessageRs] = "Cập nhật danh mục thành công";
            return RedirectToAction("Index");
        }


        public async Task<ActionResult> Del(int id)
        {
            var category = await DBContext.Instance.Categories
                .FirstOrDefaultAsync(item => item.CategoryId == id);
            if(category == null)
            {
                TempData[Constant.StatusRs] = Constant.Error;
                TempData[Constant.MessageRs] = "Danh mục không tồn tại";
                return RedirectToAction("Index");
            }
            category.Status = Constant.Inactive;
            category.UpdatedAt = DateTime.Now;
            await DBContext.Instance.SaveChangesAsync();
            TempData[Constant.StatusRs] = Constant.Success;
            TempData[Constant.MessageRs] = "Xóa danh mục thành công";
            
            return RedirectToAction("Index");
        }
    }
}

BShop/Areas/Admin/Views/CategoryMana/Add.cshtml
@using BShop.Utils
@model BShop.Models.Entity.Category

@{
    ViewBag.Title = "Thêm loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Loại sản phẩm", "Thêm loại sản phẩm" };
}

<!-- start page title -->
@Html.Partial("_PageTitle", pageTitleModel)
<!-- end page title -->

@using (Html.BeginForm("DoAdd", "CategoryMana", FormMethod.Post))
{
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- end card-body -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6">
                            <div class="mb-3">
                                <label class="form-label">Tên</label>
                                @Html.TextBoxFor(item => item.CategoryName, new { @class = "form-control", @placeholder = "Nhập tên loại" })
                            </div>
                        </div> <!-- end col-->
                    </div>
                    <button class="btn btn-sm btn-primary">Thêm</button>
                    <!-- end row -->
                </div>
            </div> <!-- end card-->
        </div> <!-- end col-->
    </div>
    <!-- end row-->
}

@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
}

BShop/Areas/Admin/Views/CategoryMana/Edit.cshtml
@using BShop.Utils
@model BShop.Models.Entity.Category

@{
    ViewBag.Title = "Chỉnh sửa loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Loại sản phẩm", "Chỉnh sửa loại sản phẩm" };
}

@Html.Partial("_PageTitle", pageTitleModel)

@using (Html.BeginForm("DoUpdate", "CategoryMana", FormMethod.Post))
{
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- end card-body -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-xl-6">
                            @Html.HiddenFor(item => item.CategoryId)
                            <div class="mb-3">
                                <label class="form-label">Tên</label>
                                @Html.TextBoxFor(item => item.CategoryName, new { @class = "form-control", @placeholder = "Nhập tên loại" })
                            </div>
                        </div> <!-- end col-->
                    </div>
                    <button class="btn btn-sm btn-primary">Sửa</button>
                    <!-- end row -->
                </div>
            </div> <!-- end card-->
        </div> <!-- end col-->
    </div>
    <!-- end row-->
}

@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
}

BShop/Areas/Admin/Views/CategoryMana/Index.cshtml
@using BShop.Utils
@model IEnumerable<BShop.Models.Entity.Category>

@{
    ViewBag.Title = "Quản lý loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var pageTitleModel = new List<string>() { "Loại sản phẩm", "Quản lý loại sản phẩm" };
}

@section css {
    <link href="~/Content/admin/dataTables.bootstrap5.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/admin/responsive.bootstrap5.css" rel="stylesheet" type="text/css"/>
}

<!-- start page title -->
@Html.Partial("_PageTitle", pageTitleModel)
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-5">
                        <a href="/Admin/CategoryMana/Add" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle me-2"></i> Thêm mới</a>
                    </div>
                    <div class="col-sm-7 d-none">
                        <div class="text-sm-end">
                            <button type="button" class="btn btn-success mb-2 me-1">
                                <i class="mdi mdi-cog"></i>
                            </button>
                            <button type="button" class="btn btn-light mb-2 me-1">Import</button>
                            <button type="button" class="btn btn-light mb-2">Export</button>
                        </div>
                    </div><!-- end col-->
                </div>
                <div class="table-responsive">
                    <table class="table table-centered table-striped dt-responsive nowrap w-100" id="products-datatable">
                        <thead>
                        <tr>
                            <th style="width: 100px;">STT</th>
                            <th>Loại sản phẩm</th>
                            <th>Ngày cập nhật cuối cùng</th>
                            <th style="width: 75px;">#</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var (value, index) in Model.Select((v, i) => (v, i)))
                        {
                            <tr>
                                <td>
                                    @(index + 1)
                                </td>
                                <td class="table-user">
                                    <a href="javascript:void(0);" class="text-body fw-semibold">@value.CategoryName</a>
                                </td>
                                <td>
                                    @(value.UpdatedAt?.ToLongDateString())
                                </td>

                                <td>
                                    <a href="/Admin/CategoryMana/Edit/@value.CategoryId" class="action-icon" title="Chỉnh sửa">
                                        <i class="mdi mdi-square-edit-outline"></i>
                                    </a>
                                    <a href="/Admin/CategoryMana/Del/@value.CategoryId" class="action-icon" title="Xóa">
                                        <i class="mdi mdi-delete"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
<!-- end row -->

@section js {
    @if (TempData[Constant.StatusRs] != null)
    {
        <script>
            showToast('@Html.Raw(TempData[Constant.MessageRs])', '@TempData[Constant.StatusRs]');
        </script>
    }
    <script src="~/Scripts/admin/category.js"></script>
}